repos:

-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      args: [--target-version=py36, --line-length=120]
      python-version: python3.6

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.720
    hooks:
    - id: mypy
      exclude: 'manage.py|tests/|settings/'
      args: [--no-strict-optional, --ignore-missing-imports]

-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.4.0
    hooks:
    -   id: python-use-type-annotations

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v1.9.1
    hooks:
    - id: pylint
      exclude: 'manage.py|tests|setup.py'
      args: [
        --max-line-length=120,
        --disable=design,
        --disable=missing-docstring,
        --disable=bad-continuation,
        --disable=max-module-lines,
        --disable=useless-super-delegation,
        --disable=import-error,
        --disable=logging-fstring-interpolation,
        --disable=invalid-name,
        --disable=duplicate-code,
        --disable=broad-except,
        --disable=logging-format-interpolation,
      ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: flake8
      args: [--max-line-length=120, '--ignore=E203,W503']
      exclude: 'manage.py'
    - id: trailing-whitespace
