version: 2.1

executors:
  python:
    docker:
      - image: circleci/python:3.6

jobs:
  pre_commit_hooks:
    executor: python
    steps:
      - checkout
      - run:
          name: Run pre-commit checks
          command: |
            sudo pip install pre-commit==1.12.0
            pre-commit run --all-files
  lad_common:
    executor: python
    steps:
      - checkout
      - run:
          name: Pip install and run test cases
          command: ./scripts/circleci_run_tests.sh lad-common

  lad_common_deploy:
    executor: python
    steps:
      - checkout
      - run:
          name: Release package
          command: |
            sudo pip install twine
            ./scripts/circleci_upload_package.sh lad-common

workflows:
  version: 2
  build_and_test_all:
    jobs:
    - pre_commit_hooks
    - lad_common:
        filters:
          tags:
            only: /^.*/
    - lad_common_deploy:
        requires:
          - lad_common
        filters:
          branches:
            only:
              - dev
              - /^release.*/
