version: "2.1"

services:
  lad-crm:
    entrypoint: /app/lad-crm/scripts/run_uwsgi.sh
    build:
      context: ../../
      dockerfile: lad-crm/Dockerfile
    container_name: lad-crm
    environment:
      TERM: xterm
    volumes:
      - ../../:/app
    ports:
      - 5000:5000
    networks:
      - lad-net
networks:
  lad-net:
    driver: bridge